export const RESET_SEARCH_LIST = 'RESET_SEARCH_LIST';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
export const ADD_TO_WATCHED = 'ADD_TO_WATCHED';
